name: Trigger Monthly Rent Reminder
on:
  schedule:
    - cron: '0 12 1 * *' # At 12pm UTC on the 1st of every month

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send reminder API call
        run: curl -v https://rentbot-q3yrsvfcoa-ue.a.run.app/reminder
